export type Location = {
  id: number,
  name: string,
  title: string,
  location: string,
  address: string,
  hours: string,
  monday: string,
  tuesday: string,
  wednesday: string,
  thursday: string,
  friday: string,
  saturday: string,
  sunday: string,
  map: string,
}